DESTINATION = ../..
PROGRAM = gb
CFLAGS = -Wall -g
LIB = -lraylib
SRC = \
	  $(DESTINATION)/devices/ppu.c \
	  $(DESTINATION)/devices/joypad.c \
	  $(DESTINATION)/debugger/debugger.c \
	  $(DESTINATION)/emu/platform/render/raylib.c \
	  emulator.c \
	  main.c \

include $(DESTINATION)/Makefile.common
