DESTINATION = ..
PROGRAM = mgb
CFLAGS = -Wall -g
LIB = -lraylib
SRC = \
	  $(DESTINATION)/platform/render/raylib.c \
	  debugger.c \
	  decoder.c \
	  interrupt.c \
	  joypad.c \
	  memory.c \
	  video.c \
	  mgb.c \
	  sm83.c \
	  sm83_isa.c \
	  timer.c \

include $(DESTINATION)/Makefile.common
